### ISSUE TITLE
Remove the messy code

### ISSUE THREAD

**Issue by lihl2011** [Field-of-Dreams-Studio/pmine.org#2]
[link](https://bbcode.pmine.org/fds-redstone_style/temp.html)

Some Chinese characters in this link are messy code. 
  e.g.:

> <html>
> <body>
> <span style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">const paratem = document.createElement("div"); paratem.classList.add("para"); paratem.style.marginTop = "5%"; paratem.innerHTML = `</span><div class="p table table-borderless" style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 74.8375px;">
> 鏍囬 |  
> -- | --
> (Optional) 鑻辫鏍囬 |  
> (Optional) 绠€鐭粙缁� |  
> (Optional) Emoji |  
> 姝ｆ枃 |  
> 娣诲姞鍒嗘DELETE
> 
> </div><span style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">` const honmo = document.createElement("tr"); honmo.innerHTML = `</span><label for="honmo" style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-size: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">姝ｆ枃</label><span style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span></span><textarea id="honmo" name="honmo" data-type="honmo" placeholder="璇疯緭鍏ユ鏂�" rows="10" cols="50" style="orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 1rem; width: 1496.8px;"></textarea><span style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">` function getparatem() { return paratem } function getsubparatem() { return subparatem } function gethonmo() { return honmo }</span>
> </body>
> </html>

(copy from _temp.html_)

  
it isn't fixed at 2024/2/29 20:49 UTC+8 ( was 'now' ).

**Comment by Redstone-D** [comment]
This is the codes from bbcode.pmine.org 
Those codes does not exist this repo :( 
But I'll fix it
